### ISSUE TITLE
Update Imgur image upload endpoint

### ISSUE THREAD

**Issue by amacado** [devicons/public-upload-to-imgur#16]
Imgur changed it's API endpoint for uploading images. The new endpoint is `https://api.imgur.com/3/upload`
Here's the API documentation provided by Imgur: https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139

As stated in the pull request https://github.com/devicons/devicon/pull/646#issuecomment-849959829 within the devicons repository our current implementation is no longer reliable.

https://github.com/devicons/public-upload-to-imgur/blob/68a069ad5f0e490593cc20e050954cb560849b9a/src/index.js#L40

We need to replace our current implementation and publish a new release of this action.

**Comment by Thomas-Boi** [comment]
It's strange, I'm testing the new URL and apparently the URL doesn't exist:
![image](https://user-images.githubusercontent.com/43018778/119901674-11d25d80-befb-11eb-9d7c-4226e588df67.png)


When I use the old URL, the endpoint complains that the id is wrong:
![image](https://user-images.githubusercontent.com/43018778/119901765-2e6e9580-befb-11eb-8804-99836ef65149.png)

I'm not too sure what's happening here. The token works just a few minutes ago with Jest.

**Comment by amacado** [comment]
I did some further research. It looks like our `/image` endpoint is still supported:
https://api.imgur.com/endpoints/image/#image-upload

![image](https://user-images.githubusercontent.com/8781699/119901819-b332d100-bf46-11eb-800d-1a7fce3d7f04.png)

**Comment by Thomas-Boi** [comment]
Here's the body that I used:
![image](https://user-images.githubusercontent.com/43018778/119901952-6d9ce680-befb-11eb-9207-6b6076608f27.png)

This was taken from the example from the Imgur API too

**Comment by amacado** [comment]
I noticed something interesting: It's not the URL/Endpoint which causes the error.
There seems to be an issue with our authorisation. When I try to send the request via Postman using our credentials sometimes the requests failes with "403 - invalid client_id". Withouth changing anything but just executing the same request multiple times: Sometimes it succeeds, sometimes it fails.

```
{
    "data": {
        "error": "Invalid client_id",
        "request": "/3/image",
        "method": "POST"
    },
    "success": false,
    "status": 403
}
```

**Comment by Thomas-Boi** [comment]
I also tested using Imgur's provided Postman code. Even their auth doesn't work:
![image](https://user-images.githubusercontent.com/43018778/119904119-a8ece480-befe-11eb-9eee-d2fa8ca92b99.png)

I'm not sure what's happening. As far as I know, our client id is correct

**Comment by Thomas-Boi** [comment]
Just retried. I set up my Postman wrong. Here's the result:
![image](https://user-images.githubusercontent.com/43018778/119905327-e488ae00-bf00-11eb-81d8-869f47556073.png)

I also set the auth field manually:
![image](https://user-images.githubusercontent.com/43018778/119905355-f4a08d80-bf00-11eb-9f42-23dcef65413c.png)

This works. However, if it re-run it, sometimes it will fail.
