### ISSUE TITLE
Discussion: Publish this Action to Marketplace

### ISSUE THREAD

**Issue by amacado** [devicons/public-upload-to-imgur#5]
We could think of publishing this action in the marketplace. 

![image](https://user-images.githubusercontent.com/8781699/103347248-beb4c580-4a96-11eb-9f7f-1e684f725b84.png)

**Comment by Thomas-Boi** [comment]
Yup for sure, I will publish it right after I update the README

**Comment by Thomas-Boi** [comment]
It seems like you will need to accept a GitHub Actions agreement before we can publish the package:

![image](https://user-images.githubusercontent.com/43018778/103377935-9ed0d200-4a95-11eb-8d2e-fc179985d69e.png)

I've upgraded the README and the script is functional so everything should be good. Can you try publishing it please? The latest stable version is v2.

**Comment by Thomas-Boi** [comment]
Hello,

I've also added an example workflow to this repo. Can you add the devicon client id into this repo as well please? This would help me test this action here rather than in the `devicon` repo. It'd also be a great way to keep docs of the process.

**Comment by amacado** [comment]
> I've also added an example workflow to this repo. Can you add the devicon client id into this repo as well please? This would help me test this action here rather than in the `devicon` repo. It'd also be a great way to keep docs of the process.

I added `IMGUR_CLIENT_ID` as secret to this repo

**Comment by amacado** [comment]
I will update `action.yml` before publishing it
![image](https://user-images.githubusercontent.com/8781699/103381065-fcdbd480-4aea-11eb-9935-17beefe586de.png)

**Comment by amacado** [comment]
Published as version 2.1.1
